# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["carine"]
  pull_request:
    branches: ["carine"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
         working-directory: ./  # Set the working directory for all steps in the job
        

    steps:
      - uses: actions/checkout@v4
      - name:   run tailwing congif.js
        run: node tailwind.config.js 
      - name:   run postcss.config.js  
        run: node postcss.config.js
      - name:   run vite.config.ts
        run: node vite.config.ts

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.1' # Use the version of Node.js you want to test against
          cache: 'npm' # Cache npm dependencies

      - name: Install dependencies
        run: npm install --prefer-offline --no-audit --progress=false

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test -- --watchAll=false --passWithNoTests --ci=true --detectOpenHandles=true --forceExit=true --maxWorkers=2 --testTimeout=30000

     