name: Node.js CI

on:
  push:
    branches: ["carine"]
  pull_request:
    branches: ["carine"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript  

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21' # Use the latest LTS version
          cache: 'npm'

      - name: Clean node_modules and cache
        run: |
           echo "Cleaning node_modules and npm cache..."
           rm -rf node_modules package-lock.json
           rm -rf ~/.npm
           npm cache clean --force
           npm install

      - name: Check and update dependencies
        run: |
          npm install -g npm-check-updates
          ncu -u
          npm install
          npm force-resolutions

      - name: Debug autoprefixer install
        run: |
          ls -la node_modules/autoprefixer || echo "autoprefixer NOT installed"

      - name: Force reinstall autoprefixer if missing
        run: |
          if [ ! -d "node_modules/autoprefixer" ]; then
            echo "Reinstalling autoprefixer..."
            npm install autoprefixer --save-dev
          else
            echo "autoprefixer is already installed."
          fi

      - name: Run ts-prune and fix vulnerabilities
        run: |
          npm install -D ts-prune
          npx ts-prune
          npm fund
          npm audit fix --force
          npm-force-resolutions

      - name: Install ts-prune globally (optional)
        run: npm install -g ts-prune
             npm-force-resolutions

      - name: Remove and reinstall problematic packages
        run: |
          npm uninstall @types/react-chartjs-2 uuid
          npm install uuid@latest
          npm fund
          npm audit fix --force
          npm audit fix
          npm-force-resolutions

      - name: Build CSS (PostCSS, Vite, etc.)
        run: npm run build
             

      - name: Run tests
        run: npm test

      - name: Final audit fix
        run: npm audit fix --force 

      - name: upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./dist # Adjust this path to your build output directory   

      - name: Perform CodeQL Analysis
        uses:  github/codeql-action/analyze@v3

          